import { CandidateProfileResponse } from '@job-pilot/shared';
import { CandidateProfileAggregate } from './repositories/candidate-profile.repository';

export function mapCandidateProfile(profile: CandidateProfileAggregate): CandidateProfileResponse {
  return {
    id: profile.id,
    userId: profile.userId,
    headline: profile.headline,
    summary: profile.summary,
    currentLocation: profile.currentLocation,
    countryCode: profile.countryCode,
    timezone: profile.timezone,
    englishLevel: profile.englishLevel,
    yearsOfExperience: profile.yearsOfExperience,
    desiredRole: profile.desiredRole,
    desiredSalaryMin: profile.desiredSalaryMin?.toNumber() ?? null,
    desiredSalaryMax: profile.desiredSalaryMax?.toNumber() ?? null,
    desiredSalaryCurrency: profile.desiredSalaryCurrency,
    remoteOnly: profile.remoteOnly,
    openToContract: profile.openToContract,
    openToFullTime: profile.openToFullTime,
    requiresVisaSponsorship: profile.requiresVisaSponsorship,
    linkedinUrl: profile.linkedinUrl,
    githubUrl: profile.githubUrl,
    portfolioUrl: profile.portfolioUrl,
    createdAt: profile.createdAt.toISOString(),
    updatedAt: profile.updatedAt.toISOString(),
    experiences: profile.experiences.map((experience) => ({
      id: experience.id,
      companyName: experience.companyName,
      roleTitle: experience.roleTitle,
      employmentType: experience.employmentType,
      location: experience.location,
      remote: experience.remote,
      startDate: experience.startDate.toISOString().slice(0, 10),
      endDate: experience.endDate?.toISOString().slice(0, 10) ?? null,
      current: experience.current,
      description: experience.description,
      achievements: experience.achievements,
      technologies: experience.technologies,
      createdAt: experience.createdAt.toISOString(),
      updatedAt: experience.updatedAt.toISOString(),
    })),
    skills: profile.candidateSkills.map((candidateSkill) => ({
      id: candidateSkill.id,
      skillId: candidateSkill.skillId,
      name: candidateSkill.skill.name,
      normalizedName: candidateSkill.skill.normalizedName,
      category: candidateSkill.skill.category,
      proficiencyLevel: candidateSkill.proficiencyLevel,
      yearsOfExperience: candidateSkill.yearsOfExperience?.toNumber() ?? null,
      lastUsedYear: candidateSkill.lastUsedYear,
      isPrimary: candidateSkill.isPrimary,
      createdAt: candidateSkill.createdAt.toISOString(),
      updatedAt: candidateSkill.updatedAt.toISOString(),
    })),
  };
}
